'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const crypto=require('node:crypto');
function fixture(){const records=new Map([['staff/manager',{role:'manager',enabled:true}],['staff/cashier',{role:'cashier',enabled:true}],['staff/disabled',{role:'manager',enabled:false}],['securityConfig/setup',{ready:true}],['securityCatalog/'+crypto.createHash('sha256').update('MH1').digest('hex'),{price:100,deleted:false}]]);const ref=p=>({path:p,get:async()=>snap(p)});const snap=p=>({exists:records.has(p),data:()=>records.get(p)});const db={doc:ref,collection:name=>({doc:id=>ref(name+'/'+id),where(){return this},limit(){return {query:true}}}),runTransaction:async fn=>{const writes=[];const result=await fn({get:async r=>r.query?{empty:true}:snap(r.path),create:(r,d)=>writes.push([r.path,d]),set:(r,d)=>writes.push([r.path,d])});writes.forEach(([p,d])=>records.set(p,d));return result;}};class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}const exports={};vm.runInNewContext(fs.readFileSync(__dirname+'/../functions/index.js','utf8'),{exports,Buffer,console,require:name=>({'firebase-admin/app':{initializeApp(){}},'firebase-admin/firestore':{getFirestore:()=>db,FieldValue:{serverTimestamp:()=>1}},'firebase-admin/auth':{getAuth:()=>({})},'firebase-functions/v2/https':{onCall:(_,handler)=>handler,HttpsError},'firebase-functions/params':{defineString:()=>({value:()=>'owner@example.com'})},'node:crypto':crypto,'./validation':require('../functions/validation')}[name])});return {records,api:exports};}
function event(type='SALE'){return {eventId:'a'.repeat(32),type,deviceId:'POS_TEST',timestamp:1,data:type==='SALE'?{id:'sale1',salesType:'Physical',arr:[{barcode:'MH1',price:100,qty:1}],subtotal:'100',discount:'0',total:'100'}:{barcode:'MH1'}};}
const req=(uid,data)=>({auth:uid?{uid,token:{}}:null,data});
test('gateway denies unauthenticated, unenrolled and disabled callers',async()=>{for(const uid of [null,'stranger','disabled']){const f=fixture();await assert.rejects(f.api.commitPosEvent(req(uid,event())),e=>['unauthenticated','permission-denied'].includes(e.code));assert.equal([...f.records.keys()].filter(k=>k.startsWith('events/')).length,0);}});
test('cashier cannot forge a manager deletion through callable API',async()=>{const f=fixture();await assert.rejects(f.api.commitPosEvent(req('cashier',event('PRODUCT_DELETE'))),e=>e.code==='permission-denied');});
test('gateway accepts a valid cashier sale exactly once and rejects ID payload changes',async()=>{const f=fixture();assert.equal((await f.api.commitPosEvent(req('cashier',event()))).duplicate,false);assert.equal((await f.api.commitPosEvent(req('cashier',event()))).duplicate,true);const changed=event();changed.data.total='50';await assert.rejects(f.api.commitPosEvent(req('cashier',changed)),e=>e.code==='already-exists');assert.equal([...f.records.keys()].filter(k=>k.startsWith('events/')).length,1);});
test('gateway denies high discounts and uninitialized setup',async()=>{const f=fixture();const e=event();e.data.discount='30';e.data.total='70';await assert.rejects(f.api.commitPosEvent(req('cashier',e)),/20%/);f.records.set('securityConfig/setup',{ready:false});await assert.rejects(f.api.commitPosEvent(req('manager',event())),/setup/);});
test('manager deletion updates the trusted catalog atomically',async()=>{const f=fixture();await f.api.commitPosEvent(req('manager',event('PRODUCT_DELETE')));assert.equal([...f.records.entries()].find(([k])=>k.startsWith('securityCatalog/'))[1].deleted,true);});
test('an unverified or unapproved identity cannot bootstrap manager access',async()=>{const f=fixture();for(const token of [{email:'owner@example.com',email_verified:false,firebase:{sign_in_provider:'google.com'}},{email:'someone@example.com',email_verified:true,firebase:{sign_in_provider:'google.com'}},{email:'owner@example.com',email_verified:true,firebase:{sign_in_provider:'anonymous'}}])await assert.rejects(f.api.managerSession({auth:{uid:'stranger',token}}),/Manager access/);assert.equal(f.records.has('staff/stranger'),false);});
